#!/usr/bin/env bash
#
# package.sh - Build a clean distributable archive of Indexhibit.
#
# Usage:
#   chmod +x package.sh
#   ./package.sh [output-filename]
#
# Default output: indexhibit-whmcs-YYYYMMDD-HHMMSS.tar.gz

set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
VERSION="$(date +%Y%m%d-%H%M%S)"
OUT="${1:-$ROOT/indexhibit-whmcs-$VERSION.tar.gz}"
OUT="$(cd "$(dirname "$OUT")" && pwd)/$(basename "$OUT")"

echo "Building archive: $OUT"

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Export the repository into the temp directory without git metadata.
if [ -d "$ROOT/.git" ]; then
    git -C "$ROOT" archive --format=tar HEAD | tar -x -C "$TMPDIR"
else
    # Fallback: copy everything except obvious source-control and dev files.
    rsync -a \
        --exclude='.git' \
        --exclude='.gitignore' \
        --exclude='.DS_Store' \
        --exclude='package.sh' \
        --exclude='WHMCS_INSTALL_PLAN.md' \
        --exclude='LAMP_INSTALLER_ANALYSIS.md' \
        "$ROOT/" "$TMPDIR/"
fi

# Add the server-side deployment helper generated by the build.
cp "$ROOT/install.sh" "$TMPDIR/install.sh" 2>/dev/null || true

# Remove development-only files that should not ship.
cd "$TMPDIR"
rm -f \
    package.sh \
    WHMCS_INSTALL_PLAN.md \
    LAMP_INSTALLER_ANALYSIS.md \
    .gitignore \
    README.md 2>/dev/null || true

# Create the archive from the temp copy.
tar -czf "$OUT" -C "$TMPDIR" .

echo "Package complete: $OUT"
